language: ruby

rvm:
  - 1.9.3

bundler_args: --without development assets
before_script:
  - psql -c 'DROP DATABASE devrv;DROP DATABASE jenkins;DROP DATABASE boauser;DROP DATABASE boatest;DROP DATABASE boadev;DROP DATABASE boastage;DROP DATABASE boaprod;DROP USER devsrv;CREATE USER devsrv WITH PASSWORD '1234';ALTER USER devsrv WITH SUPERUSER;DROP USER jenkins;CREATE USER jenkins WITH PASSWORD '1234';ALTER USER jenkins WITH jenkins;DROP USER boauser;CREATE USER boauser WITH PASSWORD 'Prof_H_No_Sn00p1ng';ALTER USER boauser WITH SUPERUSER;CREATE DATABASE jenkins OWNER jenkins;CREATE DATABASE devsrv OWNER devsrv;CREATE DATABASE boauser OWNER boauser;CREATE DATABASE boatest OWNER boauser;CREATE DATABASE boadev OWNER boauser;CREATE DATABASE boastage OWNER boauser;CREATE DATABASE boaprod OWNER boauser;' -U postgres
  - rake db:migrate