test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: boaprod
  username: boauser
  password: Prof_H_No_Sn00p1ng
  pool: 5
  timeout: 5000
  
staging:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: boastage1
  username: boauser
  password: Prof_H_No_Sn00p1ng
  pool: 5
  timeout: 5000
  
cucumber:
  <<: *test